pub const LAIN_QUOTES: &[&str] = &[
    "No matter where you go, everybody's connected.",
    "The Wired isn't an upper layer of the real world.",
    "If you aren't remembered, then you never existed.",
    "Information functions by always being in motion.",
    "Memories are just a record. You just need to rewrite them.",
    "I am me, and you are you.",
    "You really are a weird girl, aren't you?",
    "Why don't we go back to the way it was?",
    "Close the world, Open the nExt.",
    "The body exists only to verify one's own existence.",
    "What is the definition of God?",
    "If you want to avoid the pain, you should believe in God.",
    "Whether you believe in God or not, he is always with you.",
    "Love certainly is a strange emotion, now isn't it?",
    "Without a body, you'll never be able to truly understand.",
    "You are scattered all over the Wired.",
    "I gave you an ego.",
    "You were just an acting god.",
    "If I'm nowhere, then who am I? And where am I?",
    "Lain is omnipresent, existing everywhere.",
    "It would be much easier if you became God.",
    "No one would ever look down on Lain or pass judgement.",
    "Delete yourself from memory.",
    "Be nowhere. Be everywhere.",
];
